CREATE TABLE season (
    season_id INTEGER PRIMARY KEY,
    show TEXT NOT NULL,
    season_name INTEGER NOT NULL,
    date_aired TEXT,
    lead_name TEXT,
    lead_2 TEXT,
    proposal TEXT,
    still_together TEXT
);

CREATE TABLE contestant (
    contestant_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contestant_name TEXT NOT NULL,
    age INTEGER,
    hometown TEXT,
    job TEXT,
    eliminated TEXT,
    assigned_season INTEGER REFERENCES season(season_id) ON DELETE CASCADE NOT NULL,
    contestant_image TEXT 
);

